name: "release"

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: "find env"

      - uses: xresloader/upload-to-github-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "${{ github.workspace }}/gui/decky_installer.desktop;${{ github.workspace }}/gui/user_install_script.sh"
          delete_file: "random-name-*.txt"
          branches: "main;dev"
          verbose: true
          prerelease: true
